### ISSUE TITLE
`Error: Cannot read property 'disconnect' of undefined` when `wc-shadydom=true`

### ISSUE THREAD

**Issue by manolo** [PolymerElements/iron-input#104]
### Description

`detached` can be called before `attached` causing an error due that `_observer` has not yet defined. It only happens when `?wc-shadydom=true`

Found the error during the fixture initialisation when using a `paper-input`.

### Expected outcome
no error

### Actual outcome
 `Error: Cannot read property 'disconnect' of undefined` 

### Steps to reproduce
Create a test with this content
```
<!doctype html>
<html>

<head>
  <script src='../../web-component-tester/browser.js'></script>
  <link rel="import" href="../../test-fixture/test-fixture.html">
  <link rel="import" href="../../iron-test-helpers/test-helpers.html">
  <link rel="import" href="../../paper-input/paper-input.html">
</head>

<body>

<test-fixture id='test'>
  <template>
    <paper-input></paper-input>
  </template>
</test-fixture>

<script>
  describe('something', function() {
    var paperInput;

    beforeEach(function() {
      paperInput = fixture('test');
    });

    it('should just work', function() {
    });
  });
</script>

</body>
</html>

```

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
This _should_ be fixed in 6c2dd5e. Please let me know if it's not! :)
