### ISSUE TITLE
IE: Unspecified error

### ISSUE THREAD

**Issue by chimon2000** [PolymerElements/iron-input#11]
Tested on Edge version by just running the demo index page. Causes some nice epic failure.

**Comment by arthurevans** [comment]
Seeing the same issue on IE11.

**Comment by morethanreal** [comment]
Can you describe the failure you're seeing? Testing on IE11 on Windows 8, I see #20 and #19 but otherwise the input is working.

**Comment by morethanreal** [comment]
Cannot reproduce.
