### ISSUE TITLE
DOMException: Failed to execute 'define' in polymer-starter-kit

### ISSUE THREAD

**Issue by Tonkungs** [PolymerElements/iron-input#136]
### Description
 I install iron-input in  polymer-starter-kit version 4.0.0 and i found  

> Uncaught (in promise) DOMException: Failed to execute 'define' on 'CustomElementRegistry': this name has already been used with this registry
>     at Polymer (http://127.0.0.1:8081/node_modules/@polymer/polymer/lib/legacy/polymer-fn.js:43:18)
>     at http://127.0.0.1:8081/node_modules/@polymer/iron-input/node_modules/@polymer/iron-meta/iron-meta.js:131:1
> 

 ![DOMException: Failed to execute 'define' on 'CustomElementRegistry'](https://i.imgur.com/9ct63qB.png)

**Comment by nxc5929** [comment]
+ 1

**Comment by notwaldorf** [comment]
Yup, as per the first answer in the [faq](https://www.polymer-project.org/blog/2018-05-25-polymer-elements-3-faq.html), you need to make sure you don't have different versions of Polymer. Try deleting  your `node-modules` and `package.json` and reinstalling the npm dependencies

**Comment by Tonkungs** [comment]
Thk.
