### ISSUE TITLE
Cursor always jumps at end

### ISSUE THREAD

**Issue by abourget** [PolymerElements/iron-input#24]
This code creates a really annoying behavior:

    <input is="iron-input" value="{{mama}}">

When you click in the middle of the string you typed, the next character you type jumps at the end of the input field.

**Comment by abourget** [comment]
This even occurs in the plain `demo/index.html`, on Chrome Version 42.0.2311.90 (64-bit) Linux, but _doesn't show the problem_ in Firefox 38.0.. looks like a nasty one..

**Comment by morethanreal** [comment]
Appears to be fixed.
