### ISSUE TITLE
animated underline

### ISSUE THREAD

**Issue by blasten** [PolymerElements/iron-input#41]
I noticed that the underline stopped animating. is this a regression?
https://elements.polymer-project.org/elements/paper-input?view=demo:demo/index.html

**Comment by LM450N** [comment]
I think it's by design, no ? If you type a number into the first demo of Validation, the underline is animated.

**Comment by notwaldorf** [comment]
The underline comes from `paper-input`, not `iron-input`, and I think it's been fixed in the latest release.

**Comment by notwaldorf** [comment]
No longer reproducible
