### ISSUE TITLE
Firefox throws when dispatchEvent called on a `disabled` and unattached input

### ISSUE THREAD

**Issue by kevinpschaaf** [PolymerElements/iron-input#47]
Moved from https://github.com/Polymer/polymer/issues/1936.

Repro is here (fails in FF):
* iron-input repro: http://jsbin.com/dokihi/edit?html,console,output
* minimal repro using `<input disabled>`: http://jsfiddle.net/t4D7m/1/

Firefox has a bug where calling `dispatchEvent` on a non-attached and disabled input throws.

Firefox bugs:
* https://bugzilla.mozilla.org/show_bug.cgi?id=867418, which is duped to
* https://bugzilla.mozilla.org/show_bug.cgi?id=329509, which is a 9-year old bug

This can happen when any `notify: true` value is set on a disabled input type extension before attached, which can happen via a binding, during configuration of a default value, or by setting a property in `ready` when it is in the local-DOM of another element (since it won't be attached until after `ready`).

After considering how we'd fix this bug in Polymer core, we decided we'd rather just fix it locally in `iron-input` for now, to avoid adding a complex whitelist system in Polymer core to work around this Firefox bug.  If this becomes more of a problem outside of `iron-input` we can consider a more general solution.

**Comment by srikkbhat** [comment]
Is there any workaround for this? My app does not even load in firefox and I don't know when this issue is going to be fixed.

**Comment by FLamparski** [comment]
Is this released yet?

**Comment by notwaldorf** [comment]
@FLamparski Yup!
