### ISSUE TITLE
html comment inside js comment breaking gulp-vulcanize build.

### ISSUE THREAD

**Issue by runia1** [PolymerElements/iron-input#83]
The html comment \ towards the bottom of iron-input.html's js comment is breaking my build when I run 

$ gulp default

Changing that line in the comment block to:

only allow characters that match [0-9]

Fixes it.  May be my IDE, if no one else is having that issue.  I use phpstorm 10.0.3

**Comment by azakus** [comment]
Can you post some reproduction steps? Are you using Polymer Start Kit?

**Comment by notwaldorf** [comment]
Closing, since there hasn't been an answer. Please re-open if you can provide some repro steps. Thanks!
