### ISSUE TITLE
_updateValueAndPreserveCaret doesn't set this.inputElement.value on exception

### ISSUE THREAD

**Issue by coreyfarrell** [PolymerElements/iron-input#99]
### Description
_updateValueAndPreserveCaret sets this.value when an exception occurs, needs to set this.inputElement.value.

### Steps to reproduce

Add `<paper-input type="email" value="{{dataValue}}"></paper-input>` to a template where `dataValue` is set to an email address.  `_updateValueAndPreserveCaret` throws an exception when trying to read `this.inputElement.selectionStart`, but the catch block doesn't set value on the inputElement.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment]
fixed by #100
